package transpile

import (
	"fmt"
	"strings"

	tsmorph "github.com/jclyons52/ts-go-morph"
	"github.com/jclyons52/ts-go-morph/third_party/typescript-go/ts/ast"
)

// emitPreamble writes the package clause and the stdlib imports that the
// emitted code actually references.
func (tr *transpiler) emitPreamble() error {
	tr.out.line("// Code generated by ts2go from TypeScript. DO NOT EDIT.")
	tr.out.line("")
	tr.out.line("package main")
	tr.out.blank()
	var imports []string
	for _, pkg := range []string{"fmt", "strings", "math", "maps"} {
		if tr.used[pkg] {
			imports = append(imports, `"`+pkg+`"`)
		}
	}
	if len(imports) > 0 {
		tr.out.line("import (")
		tr.out.indent()
		for _, i := range imports {
			tr.out.line(i)
		}
		tr.out.dedent()
		tr.out.line(")")
		tr.out.blank()
	}
	return nil
}

// transpileStatement dispatches a top-level (or nested) statement.
func (tr *transpiler) transpileStatement(n tsmorph.Node, topLevel bool) error {
	switch {
	case ast.IsInterfaceDeclaration(n.ASTNode()):
		return tr.emitInterface(n)
	case ast.IsClassDeclaration(n.ASTNode()):
		return tr.emitClass(n)
	case ast.IsEnumDeclaration(n.ASTNode()):
		return tr.emitEnum(n)
	case ast.IsTypeAliasDeclaration(n.ASTNode()):
		return tr.emitTypeAlias(n)
	case ast.IsFunctionDeclaration(n.ASTNode()):
		return tr.emitFunction(n)
	case ast.IsVariableStatement(n.ASTNode()):
		return tr.emitVariableStatement(n)
	case ast.IsImportDeclaration(n.ASTNode()), ast.IsExportDeclaration(n.ASTNode()):
		// Imports/exports map to nothing in v1 (single-package output).
		return nil
	default:
		return tr.emitStatement(n)
	}
}

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

// emitInterface emits `interface X { ... }` as a Go struct (data members) or
// a Go interface (method members).
func (tr *transpiler) emitInterface(n tsmorph.Node) error {
	name := n.Name()
	members := n.GetMembers()

	hasMethods := false
	for _, m := range members {
		if ast.IsMethodSignatureDeclaration(m.ASTNode()) ||
			ast.IsCallSignatureDeclaration(m.ASTNode()) ||
			ast.IsConstructSignatureDeclaration(m.ASTNode()) {
			hasMethods = true
			break
		}
	}
	if !hasMethods {
		// Pure data interface → struct.
		tr.out.line("type " + name + " struct {")
		tr.out.indent()
		for _, m := range members {
			if err := tr.emitInterfaceMember(m); err != nil {
				return err
			}
		}
		tr.out.dedent()
		tr.out.line("}")
		tr.out.blank()
		return nil
	}
	// Interface with methods → Go interface.
	tr.out.line("type " + name + " interface {")
	tr.out.indent()
	for _, m := range members {
		if ast.IsMethodSignatureDeclaration(m.ASTNode()) {
			params, ret, err := tr.signatureFromChildren(m)
			if err != nil {
				return err
			}
			tr.out.line(m.Name() + "(" + params + ")" + ret)
		}
	}
	tr.out.dedent()
	tr.out.line("}")
	tr.out.blank()
	return nil
}

func (tr *transpiler) emitInterfaceMember(m tsmorph.Node) error {
	name := exportField(m.Name())
	if tn, ok := m.GetType(); ok {
		typ, err := tr.goType(tn)
		if err != nil {
			return err
		}
		if typ == "" {
			typ = "any"
		}
		tr.out.line(name + " " + typ)
		return nil
	}
	typ := m.Type()
	if typ.IsUnknown() {
		return fmt.Errorf("interface member %s has no type", name)
	}
	tr.out.line(name + " " + tr.cleanCheckerType(typ.Text()))
	return nil
}

// ---------------------------------------------------------------------------
// Classes
// ---------------------------------------------------------------------------

// emitClass emits `class X { ... }` as a Go struct + methods. The constructor
// becomes NewX(...). `extends` becomes struct embedding.
func (tr *transpiler) emitClass(n tsmorph.Node) error {
	name := n.Name()

	// extends → embedded field.
	var embedded []string
	if ext, ok := tr.extendsName(n); ok {
		embedded = append(embedded, ext)
	}

	tr.out.line("type " + name + " struct {")
	tr.out.indent()
	for _, e := range embedded {
		tr.out.line(e)
	}
	// Regular properties.
	for _, p := range n.GetMembers() {
		if !ast.IsPropertyDeclaration(p.ASTNode()) && !ast.IsPropertySignatureDeclaration(p.ASTNode()) {
			continue
		}
		fname := exportField(p.Name())
		tn, ok := p.GetType()
		if !ok {
			typ := p.Type()
			tr.out.line(fname + " " + tr.cleanCheckerType(typ.Text()))
			continue
		}
		typ, err := tr.goType(tn)
		if err != nil {
			return err
		}
		if typ == "" {
			typ = "any"
		}
		tr.out.line(fname + " " + typ)
	}
	// Constructor parameter properties (`constructor(private name: string)`)
	// declare fields too.
	for _, m := range n.GetMembers() {
		if !ast.IsConstructorDeclaration(m.ASTNode()) {
			continue
		}
		for _, c := range m.Children() {
			if !ast.IsParameterDeclaration(c.ASTNode()) {
				continue
			}
			if !c.HasModifierPrivate() && !c.HasModifierProtected() &&
				!c.HasModifier(ast.ModifierFlagsPublic) && !c.HasModifier(ast.ModifierFlagsReadonly) {
				continue
			}
			pname := exportField(c.Name())
			tn, ok := c.GetType()
			if !ok {
				tr.out.line(pname + " " + tr.cleanCheckerType(c.Type().Text()))
				continue
			}
			typ, err := tr.goType(tn)
			if err != nil {
				return err
			}
			if typ == "" {
				typ = "any"
			}
			tr.out.line(pname + " " + typ)
		}
	}
	tr.out.dedent()
	tr.out.line("}")
	tr.out.blank()

	// Constructor → NewX(params) returning *X.
	for _, m := range n.GetMembers() {
		if !ast.IsConstructorDeclaration(m.ASTNode()) {
			continue
		}
		params, _, err := tr.signatureFromChildren(m)
		if err != nil {
			return err
		}
		tr.out.line("func New" + name + "(" + params + ") *" + name + " {")
		tr.out.indent()
		tr.out.line("r := &" + name + "{}")
		// Parameter properties: `constructor(private name: string)` assigns
		// the parameter to the generated field.
		for _, c := range m.Children() {
			if !ast.IsParameterDeclaration(c.ASTNode()) {
				continue
			}
			if !c.HasModifierPrivate() && !c.HasModifierProtected() &&
				!c.HasModifier(ast.ModifierFlagsPublic) && !c.HasModifier(ast.ModifierFlagsReadonly) {
				continue
			}
			pname := c.Name()
			tr.out.line("r." + exportField(pname) + " = " + pname)
		}
		tr.out.line("return r")
		tr.out.dedent()
		tr.out.line("}")
		tr.out.blank()
	}

	// Methods.
	for _, m := range n.GetMembers() {
		if !ast.IsMethodDeclaration(m.ASTNode()) {
			continue
		}
		if err := tr.emitMethod(name, m); err != nil {
			return err
		}
	}
	return nil
}

// extendsName returns the base class name from a class heritage clause.
func (tr *transpiler) extendsName(n tsmorph.Node) (string, bool) {
	for _, c := range n.Children() {
		if ast.IsHeritageClause(c.ASTNode()) {
			for _, t := range c.GetTypeArguments() {
				_ = t
			}
			for _, cc := range c.Children() {
				if ast.IsExpressionWithTypeArguments(cc.ASTNode()) {
					return cc.Name(), true
				}
			}
		}
	}
	return "", false
}

// emitMethod emits a Go method: `func (r *X) name(params) ret { body }`.
func (tr *transpiler) emitMethod(recv string, m tsmorph.Node) error {
	mname := m.Name()
	params, ret, err := tr.signatureFromChildren(m)
	if err != nil {
		return err
	}
	tr.out.line("func (r *" + recv + ") " + mname + "(" + params + ")" + ret + " {")
	tr.out.indent()
	if body, ok := m.GetBody(); ok {
		if err := tr.emitBlock(body); err != nil {
			return err
		}
	} else {
		tr.out.line("panic(\"not implemented\")")
	}
	tr.out.dedent()
	tr.out.line("}")
	tr.out.blank()
	return nil
}

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

// emitEnum emits a TS enum as a Go typed constant block with iota.
func (tr *transpiler) emitEnum(n tsmorph.Node) error {
	name := n.Name()
	members := n.GetMembers()

	isString := false
	for _, m := range members {
		if init, ok := m.GetInitializer(); ok {
			if strings.HasPrefix(strings.TrimSpace(init.Text()), `"`) {
				isString = true
				break
			}
		}
	}

	tr.out.line("type " + name + " int")
	tr.out.blank()
	tr.out.line("const (")
	tr.out.indent()
	if isString {
		for _, m := range members {
			init, ok := m.GetInitializer()
			if !ok {
				continue
			}
			tr.out.line(name + m.Name() + " " + name + " = " + strings.TrimSpace(init.Text()))
		}
	} else {
		tr.out.line(name + "Unspecified " + name + " = iota")
		for _, m := range members {
			tr.out.line(name + m.Name())
		}
	}
	tr.out.dedent()
	tr.out.line(")")
	tr.out.blank()
	return nil
}

// ---------------------------------------------------------------------------
// Type aliases
// ---------------------------------------------------------------------------

// emitTypeAlias emits `type X = T` as `type X = T` (Go alias). Aliases whose
// names are already Go builtins (uint8, int64, ...) are skipped — the
// builtin IS the target, and `type uint8 = uint8` would be recursive.
func (tr *transpiler) emitTypeAlias(n tsmorph.Node) error {
	name := n.Name()
	info, ok := tr.aliases[name]
	if !ok {
		return fmt.Errorf("alias %s not collected", name)
	}
	if _, isBuiltin := primitiveAliases[name]; isBuiltin {
		return nil
	}
	tr.out.line("type " + name + " = " + info.target)
	tr.out.blank()
	return nil
}

// ---------------------------------------------------------------------------
// Functions
// ---------------------------------------------------------------------------

// emitFunction emits a top-level function declaration.
func (tr *transpiler) emitFunction(n tsmorph.Node) error {
	name := n.Name()
	params, ret, err := tr.signatureFromChildren(n)
	if err != nil {
		return err
	}
	tr.out.line("func " + name + "(" + params + ")" + ret + " {")
	tr.out.indent()
	if body, ok := n.GetBody(); ok {
		if err := tr.emitBlock(body); err != nil {
			return err
		}
	} else {
		tr.out.line("panic(\"not implemented\")")
	}
	tr.out.dedent()
	tr.out.line("}")
	tr.out.blank()
	return nil
}

// emitVariableStatement emits `const x = ...` / `let x: T = ...`.
func (tr *transpiler) emitVariableStatement(n tsmorph.Node) error {
	vs, _ := n.AsVariableStatement()
	for _, d := range vs.Declarations() {
		name := d.Name()
		init, hasInit := d.Initializer()
		tn, hasType := d.TypeNode()
		var typ string
		if hasType {
			t, err := tr.goType(tn)
			if err != nil {
				return err
			}
			typ = t
		}
		if hasInit {
			// Object literals with a declared type → typed struct literal
			// (the checker types the literal as an anonymous __object).
			if ast.IsObjectLiteralExpression(init.ASTNode()) && typ != "" && typ != "any" {
				expr, err := tr.typedObjectLiteral(init, typ)
				if err != nil {
					return err
				}
				tr.out.line("var " + name + " " + typ + " = " + expr)
				continue
			}
			expr, err := tr.emitExpr(init)
			if err != nil {
				return err
			}
			if typ != "" && typ != "any" {
				tr.out.line("var " + name + " " + typ + " = " + expr)
			} else {
				tr.out.line(name + " := " + expr)
			}
		} else if typ != "" {
			tr.out.line("var " + name + " " + typ)
		}
	}
	return nil
}

// ---------------------------------------------------------------------------
// Signature helpers
// ---------------------------------------------------------------------------

// signatureFromChildren renders `params) ret` from a node's parameter
// children and call-signature return type. The declared return type node is
// preferred over the checker's text so aliases (Money, uint8) survive.
func (tr *transpiler) signatureFromChildren(n tsmorph.Node) (params, ret string, err error) {
	var ps []string
	for _, c := range n.Children() {
		if !ast.IsParameterDeclaration(c.ASTNode()) {
			continue
		}
		name := c.Name()
		tn, ok := c.GetType()
		var typ string
		if ok {
			t, err := tr.goType(tn)
			if err != nil {
				return "", "", err
			}
			typ = t
		} else {
			typ = "any"
		}
		ps = append(ps, name+" "+typ)
	}
	ret = ""
	// Declared return type (syntax-first: keeps alias names).
	if rn, ok := tr.returnTypeNode(n); ok {
		t, err := tr.goType(rn)
		if err != nil {
			return "", "", err
		}
		if t != "" {
			ret = " " + t
			return strings.Join(ps, ", "), ret, nil
		}
	}
	sigs := n.Type().CallSignatures()
	if len(sigs) > 0 && !sigs[0].ReturnType().IsVoid() {
		ret = " " + tr.cleanCheckerType(sigs[0].ReturnType().Text())
	}
	return strings.Join(ps, ", "), ret, nil
}

// returnTypeNode finds the declared return-type child of a function-like
// node (the type node following the parameter list).
func (tr *transpiler) returnTypeNode(n tsmorph.Node) (tsmorph.Node, bool) {
	// ts-go-morph's typed wrappers expose ReturnTypeNode directly.
	switch {
	case ast.IsFunctionDeclaration(n.ASTNode()):
		if fd, ok := n.AsFunctionDeclaration(); ok {
			return fd.ReturnTypeNode()
		}
	case ast.IsMethodDeclaration(n.ASTNode()):
		if md, ok := n.AsMethodDeclaration(); ok {
			return md.ReturnTypeNode()
		}
	}
	// Generic fallback: any type node after the parameter list is the return
	// type.
	for _, c := range n.Children() {
		if ast.IsTypeNode(c.ASTNode()) {
			if isTypeNodeAfterParams(n, c) {
				return c, true
			}
		}
	}
	return tsmorph.Node{}, false
}

// isTypeNodeAfterParams reports whether the type node appears after the
// node's parameter list (i.e. it is the return type, not a param type).
func isTypeNodeAfterParams(n, tn tsmorph.Node) bool {
	lastParamEnd := -1
	for _, c := range n.Children() {
		if ast.IsParameterDeclaration(c.ASTNode()) {
			if c.End() > lastParamEnd {
				lastParamEnd = c.End()
			}
		}
	}
	return lastParamEnd >= 0 && tn.Pos() > lastParamEnd
}
