package transpile

import (
	"fmt"
	"slices"
	"strconv"
	"strings"

	tsmorph "github.com/jclyons52/ts-go-morph"
	"github.com/jclyons52/ts-go-morph/third_party/typescript-go/ts/ast"
)

// emitPreamble writes the package clause, the post-work manifest (so the
// LLM's TODO list travels with the code), and the stdlib imports that the
// emitted code actually references.
func (tr *transpiler) emitPreamble() error {
	tr.out.line("// Code generated by ts2go from TypeScript. DO NOT EDIT.")
	tr.out.blank()
	if m := tr.buildReport(true).Manifest(); m != "" {
		for _, l := range strings.Split(strings.TrimSuffix(m, "\n"), "\n") {
			tr.out.line(l)
		}
		tr.out.blank()
	}
	tr.out.line("package " + tr.pkgName)
	tr.out.blank()
	var imports []string
	for _, pkg := range []string{"fmt", "strings", "math", "maps", "strconv", "errors", "regexp"} {
		if tr.used[pkg] {
			imports = append(imports, `"`+pkg+`"`)
		}
	}
	if tr.usedShim && tr.emitShim {
		// The shim source is appended to this file and needs these; when
		// the shim lives in its own file (multi-file packages) it declares
		// its own imports.
		for _, pkg := range []string{"fmt", "sync", "time", "reflect", "regexp", "strings"} {
			if !slices.Contains(imports, `"`+pkg+`"`) {
				imports = append(imports, `"`+pkg+`"`)
			}
		}
	}
	slices.Sort(imports)
	if len(imports) > 0 {
		tr.out.line("import (")
		tr.out.indent()
		for _, i := range imports {
			tr.out.line(i)
		}
		tr.out.dedent()
		tr.out.line(")")
		tr.out.blank()
	}
	return nil
}

// transpileStatement dispatches a top-level (or nested) statement.
func (tr *transpiler) transpileStatement(n tsmorph.Node, topLevel bool) error {
	switch {
	case ast.IsInterfaceDeclaration(n.ASTNode()):
		return tr.emitInterface(n)
	case ast.IsClassDeclaration(n.ASTNode()):
		return tr.emitClass(n)
	case ast.IsEnumDeclaration(n.ASTNode()):
		return tr.emitEnum(n)
	case ast.IsTypeAliasDeclaration(n.ASTNode()):
		return tr.emitTypeAlias(n)
	case ast.IsFunctionDeclaration(n.ASTNode()):
		return tr.emitFunction(n)
	case ast.IsVariableStatement(n.ASTNode()):
		// `const x = require("...")` — treat require like an import.
		if tr.handleCommonJSRequireStatement(n) {
			return nil
		}
		return tr.emitVariableStatement(n)
	case ast.IsImportDeclaration(n.ASTNode()):
		return tr.handleImport(n)
	case ast.IsExportDeclaration(n.ASTNode()):
		return tr.handleExport(n)
	default:
		return tr.emitStatement(n)
	}
}

// importBindingNames extracts the local identifiers bound by an import
// declaration: `import fs from "x"`, `import {a, b as c} from "x"`,
// `import * as ns from "x"`. Side-effect imports (`import "x"`) bind none.
func importBindingNames(txt string) []string {
	body := strings.TrimSpace(txt)
	body = strings.TrimSpace(strings.TrimPrefix(body, "import"))
	if i := strings.Index(body, "from"); i >= 0 {
		body = body[:i]
	}
	body = strings.TrimSpace(strings.Trim(body, "\"'`"))
	if body == "" || body == "{" {
		return nil
	}
	if strings.HasPrefix(body, "*") {
		// `* as ns`
		body = strings.Replace(body, "* as ", "", 1)
	}
	body = strings.Trim(body, "{}")
	var out []string
	for _, part := range strings.Split(body, ",") {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		if j := strings.Index(part, " as "); j >= 0 {
			part = strings.TrimSpace(part[j+4:])
		}
		part = strings.TrimSpace(strings.Trim(part, "\"'`"))
		if part != "" {
			out = append(out, part)
		}
	}
	return out
}

// handleImport maps a TS import to nothing (Go packages have no import
// statements for same-package files): imports that resolve to another file
// of the same Go package are dropped — the identifiers resolve directly —
// while imports of sibling packages and external modules become work items
// the LLM must wire up.
func (tr *transpiler) handleImport(n tsmorph.Node) error {
	spec := tr.moduleSpecifier(n)
	if spec == "" {
		return nil
	}
	// Bindings from this import are unresolved (sibling/external) regardless
	// of classification in single-file mode; record them so dynamic-any
	// routing leaves them as resilience placeholders.
	if tr.external == nil {
		tr.external = map[string]bool{}
	}
	for _, nm := range importBindingNames(n.Text()) {
		tr.external[nm] = true
	}
	if tr.classify == nil {
		return nil // single-file mode: imports were always dropped
	}
	cls, target := tr.classify(tr.sf.FilePath(), spec)
	switch cls {
	case importSamePackage:
		return nil
	case importSiblingPackage:
		tr.recordGap(SevTodo, "import", n, "cross-package import %q — wire up the Go import (package %s)", spec, target)
	default:
		tr.recordGap(SevTodo, "import", n, "external module import %q — port or stub this module", spec)
	}
	return nil
}

// handleExport maps a TS export to nothing: exported names are already
// emitted as exported Go identifiers (PascalCase). Re-exports from sibling
// packages or external modules become work items.
func (tr *transpiler) handleExport(n tsmorph.Node) error {
	spec := tr.moduleSpecifier(n)
	if spec == "" {
		return nil
	}
	if tr.classify == nil {
		return nil
	}
	cls, target := tr.classify(tr.sf.FilePath(), spec)
	switch cls {
	case importSamePackage:
		return nil
	case importSiblingPackage:
		tr.recordGap(SevTodo, "import", n, "re-export from sibling package %q — wire up the Go import (package %s)", spec, target)
	default:
		tr.recordGap(SevTodo, "import", n, "re-export from external module %q — port or stub this module", spec)
	}
	return nil
}

// moduleSpecifier returns the module specifier text of an import/export
// declaration, or "" when the declaration has none (e.g. `export { a }`).
func (tr *transpiler) moduleSpecifier(n tsmorph.Node) string {
	node := n.ASTNode()
	if node == nil {
		return ""
	}
	ms := ast.GetExternalModuleName(node)
	if ms == nil {
		return ""
	}
	return strings.Trim(ms.Text(), `"'`)
}

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

// emitInterface emits `interface X { ... }` as a Go struct (data members) or
// a Go interface (method members).
func (tr *transpiler) emitInterface(n tsmorph.Node) error {
	name := n.Name()
	members := n.GetMembers()

	hasMethods := false
	for _, m := range members {
		if ast.IsMethodSignatureDeclaration(m.ASTNode()) ||
			ast.IsCallSignatureDeclaration(m.ASTNode()) ||
			ast.IsConstructSignatureDeclaration(m.ASTNode()) {
			hasMethods = true
			break
		}
	}
	if !hasMethods {
		// Pure data interface → struct.
		tr.out.line("type " + name + " struct {")
		tr.out.indent()
		for _, m := range members {
			if err := tr.emitInterfaceMember(m); err != nil {
				return err
			}
		}
		tr.out.dedent()
		tr.out.line("}")
		tr.out.blank()
		return nil
	}
	// Interface with methods → Go interface.
	tr.out.line("type " + name + " interface {")
	tr.out.indent()
	for _, m := range members {
		if ast.IsMethodSignatureDeclaration(m.ASTNode()) {
			params, ret, err := tr.signatureFromChildren(m)
			if err != nil {
				return err
			}
			tr.out.line(m.Name() + "(" + params + ")" + ret)
		}
	}
	tr.out.dedent()
	tr.out.line("}")
	tr.out.blank()
	return nil
}

func (tr *transpiler) emitInterfaceMember(m tsmorph.Node) error {
	name := exportField(m.Name())
	typ, err := tr.memberType(m)
	if err != nil {
		return err
	}
	tr.out.line(name + " " + typ)
	return nil
}

// memberType computes the Go field type for an interface/class member,
// mapping optional (`x?: T`) to a pointer with an approx gap.
func (tr *transpiler) memberType(m tsmorph.Node) (string, error) {
	tn, ok := m.GetType()
	var typ string
	var err error
	if ok {
		typ, err = tr.goType(tn)
	} else {
		t := m.Type()
		if t.IsUnknown() {
			return "", fmt.Errorf("member %s has no type", m.Name())
		}
		typ = tr.cleanCheckerType(t.Text())
	}
	if err != nil {
		return "", err
	}
	if typ == "" {
		typ = "any"
	}
	if m.HasQuestionToken() {
		tr.recordGap(SevApprox, "optional", m, "optional property %s mapped to pointer", m.Name())
		typ = "*" + typ
	}
	return typ, nil
}

// ---------------------------------------------------------------------------
// Classes
// ---------------------------------------------------------------------------

// emitClass emits `class X { ... }` as a Go struct + methods. The constructor
// becomes NewX(...). `extends` becomes struct embedding.
func (tr *transpiler) emitClass(n tsmorph.Node) error {
	name := n.Name()

	// extends → embedded field.
	var embedded []string
	if ext, ok := tr.extendsName(n); ok {
		embedded = append(embedded, ext)
	}

	tr.out.line("type " + name + " struct {")
	tr.out.indent()
	for _, e := range embedded {
		tr.out.line(e)
	}
	// Regular properties.
	for _, p := range n.GetMembers() {
		if !ast.IsPropertyDeclaration(p.ASTNode()) && !ast.IsPropertySignatureDeclaration(p.ASTNode()) {
			continue
		}
		fname := exportField(p.Name())
		typ, err := tr.memberType(p)
		if err != nil {
			return err
		}
		tr.out.line(fname + " " + typ)
	}
	// Constructor parameter properties (`constructor(private name: string)`)
	// declare fields too.
	for _, m := range n.GetMembers() {
		if !ast.IsConstructorDeclaration(m.ASTNode()) {
			continue
		}
		for _, c := range m.Children() {
			if !ast.IsParameterDeclaration(c.ASTNode()) {
				continue
			}
			if !c.HasModifierPrivate() && !c.HasModifierProtected() &&
				!c.HasModifier(ast.ModifierFlagsPublic) && !c.HasModifier(ast.ModifierFlagsReadonly) {
				continue
			}
			pname := exportField(c.Name())
			tn, ok := c.GetType()
			if !ok {
				tr.out.line(pname + " " + tr.cleanCheckerType(c.Type().Text()))
				continue
			}
			typ, err := tr.goType(tn)
			if err != nil {
				return err
			}
			if typ == "" {
				typ = "any"
			}
			tr.out.line(pname + " " + typ)
		}
	}
	tr.out.dedent()
	tr.out.line("}")
	tr.out.blank()

	// Constructor → NewX(params) returning *X.
	for _, m := range n.GetMembers() {
		if !ast.IsConstructorDeclaration(m.ASTNode()) {
			continue
		}
		params, _, err := tr.signatureFromChildren(m)
		if err != nil {
			return err
		}
		tr.out.line("func New" + name + "(" + params + ") *" + name + " {")
		tr.out.indent()
		tr.out.line("r := &" + name + "{}")
		// Parameter properties: `constructor(private name: string)` assigns
		// the parameter to the generated field.
		for _, c := range m.Children() {
			if !ast.IsParameterDeclaration(c.ASTNode()) {
				continue
			}
			if !c.HasModifierPrivate() && !c.HasModifierProtected() &&
				!c.HasModifier(ast.ModifierFlagsPublic) && !c.HasModifier(ast.ModifierFlagsReadonly) {
				continue
			}
			pname := c.Name()
			tr.out.line("r." + exportField(pname) + " = " + pname)
		}
		tr.out.line("return r")
		tr.out.dedent()
		tr.out.line("}")
		tr.out.blank()
	}

	// Methods.
	for _, m := range n.GetMembers() {
		if !ast.IsMethodDeclaration(m.ASTNode()) {
			continue
		}
		if err := tr.emitMethod(name, m); err != nil {
			return err
		}
	}
	return nil
}

// extendsName returns the base class name from a class heritage clause.
func (tr *transpiler) extendsName(n tsmorph.Node) (string, bool) {
	for _, c := range n.Children() {
		if ast.IsHeritageClause(c.ASTNode()) {
			for _, t := range c.GetTypeArguments() {
				_ = t
			}
			for _, cc := range c.Children() {
				if ast.IsExpressionWithTypeArguments(cc.ASTNode()) {
					return cc.Name(), true
				}
			}
		}
	}
	return "", false
}

// emitMethod emits a Go method: `func (r *X) name(params) ret { body }`.
// Async methods are wrapped in the jsrt shim like async functions.
func (tr *transpiler) emitMethod(recv string, m tsmorph.Node) error {
	mname := m.Name()
	params, ret, err := tr.signatureFromChildren(m)
	if err != nil {
		return err
	}
	isAsync := m.HasModifier(ast.ModifierFlagsAsync)
	if isAsync {
		tr.usedShim = true
		ret = " *jsrtPromise"
	}
	tr.retStack = append(tr.retStack, strings.TrimSpace(ret))
	defer func() { tr.retStack = tr.retStack[:len(tr.retStack)-1] }()
	if isAsync {
		tr.recordGap(SevApprox, "async", m, "async method via jsrt shim (goroutine-per-call); swap for native concurrency later")
		tr.retStack[len(tr.retStack)-1] = "any"
		tr.out.line("func (r *" + recv + ") " + mname + "(" + params + ")" + ret + " {")
		tr.out.indent()
		tr.out.line("return jsrtAsync(func() any {")
		tr.out.indent()
		if body, ok := m.GetBody(); ok {
			if err := tr.emitBlock(body); err != nil {
				return err
			}
		} else {
			tr.out.line("panic(\"not implemented\")")
		}
		tr.out.dedent()
		tr.out.line("})")
		tr.out.dedent()
		tr.out.line("}")
		tr.out.blank()
		return nil
	}
	tr.out.line("func (r *" + recv + ") " + mname + "(" + params + ")" + ret + " {")
	tr.out.indent()
	if body, ok := m.GetBody(); ok {
		if err := tr.emitBlock(body); err != nil {
			return err
		}
	} else {
		tr.out.line("panic(\"not implemented\")")
	}
	tr.out.dedent()
	tr.out.line("}")
	tr.out.blank()
	return nil
}

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

// emitEnum emits a TS enum as a Go typed constant block. Numeric enums get
// explicit values matching TS semantics (initializers respected, implicit
// members continue from the previous + 1); string enums become a named
// string type with string constants.
func (tr *transpiler) emitEnum(n tsmorph.Node) error {
	name := n.Name()
	members := n.GetMembers()

	isString := false
	for _, m := range members {
		if init, ok := m.GetInitializer(); ok {
			if strings.HasPrefix(strings.TrimSpace(init.Text()), `"`) ||
				strings.HasPrefix(strings.TrimSpace(init.Text()), `'`) {
				isString = true
				break
			}
		}
	}

	if isString {
		tr.out.line("type " + name + " string")
		tr.out.blank()
		tr.out.line("const (")
		tr.out.indent()
		for _, m := range members {
			v := ""
			if init, ok := m.GetInitializer(); ok {
				v = normalizeQuote(strings.TrimSpace(init.Text()))
			} else {
				// TS requires initializers on string enums; if missing, fall
				// back to the member name so output still compiles.
				v = `"` + m.Name() + `"`
			}
			tr.out.line(name + exportField(m.Name()) + " " + name + " = " + v)
		}
		tr.out.dedent()
		tr.out.line(")")
		tr.out.blank()
		return nil
	}

	// Numeric enum: emit explicit values (TS folds initializers; implicit
	// members continue from previous + 1), so `Savings = 5, Credit` → 5, 6.
	tr.out.line("type " + name + " int")
	tr.out.blank()
	tr.out.line("const (")
	tr.out.indent()
	value := 0
	for _, m := range members {
		v := value
		if init, ok := m.GetInitializer(); ok {
			t := strings.TrimSpace(init.Text())
			if parsed, err := strconv.Atoi(t); err == nil {
				v = parsed
			} else {
				// Non-literal initializer: emit verbatim for the LLM.
				tr.recordGap(SevTodo, "enum", m, "enum member %s.%s has non-literal initializer", name, m.Name())
				tr.out.line(name + exportField(m.Name()) + " " + name + " = " + t + " // TODO(ts2go): verify value")
				value++
				continue
			}
		}
		tr.out.line(name + exportField(m.Name()) + " " + name + " = " + strconv.Itoa(v))
		value = v + 1
	}
	tr.out.dedent()
	tr.out.line(")")
	tr.out.blank()
	return nil
}

// ---------------------------------------------------------------------------
// Type aliases
// ---------------------------------------------------------------------------

// emitTypeAlias emits `type X = T` as `type X = T` (Go alias). Aliases whose
// names are already Go builtins (uint8, int64, ...) are skipped — the
// builtin IS the target, and `type uint8 = uint8` would be recursive.
// String-literal-union aliases become a named string type + consts.
func (tr *transpiler) emitTypeAlias(n tsmorph.Node) error {
	name := n.Name()
	info, ok := tr.aliases[name]
	if !ok {
		return fmt.Errorf("alias %s not collected", name)
	}
	if info.unionValues != nil {
		tr.out.line("type " + name + " string")
		tr.out.blank()
		tr.out.line("const (")
		tr.out.indent()
		for _, v := range info.unionValues {
			tr.out.line(name + unionConstSuffix(v) + " " + name + " = " + v)
		}
		tr.out.dedent()
		tr.out.line(")")
		tr.out.blank()
		return nil
	}
	if _, isBuiltin := primitiveAliases[name]; isBuiltin {
		return nil
	}
	tr.out.line("type " + name + " = " + info.target)
	tr.out.blank()
	return nil
}

// unionConstSuffix turns a quoted literal into an exported const-name
// suffix: `"active"` → `Active`, `"in-progress"` → `InProgress`.
func unionConstSuffix(quoted string) string {
	s := strings.Trim(quoted, `"`)
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return !('a' <= r && r <= 'z' || 'A' <= r && r <= 'Z' || '0' <= r && r <= '9')
	})
	var b strings.Builder
	for _, p := range parts {
		b.WriteString(exportField(p))
	}
	if b.Len() == 0 {
		return "Value"
	}
	return b.String()
}

// ---------------------------------------------------------------------------
// Functions
// ---------------------------------------------------------------------------

// emitFunction emits a top-level function declaration. `async` functions
// are wrapped in the jsrt shim: the body runs in a goroutine returning a
// promise, with await mapped to jsrtAwait inside.
func (tr *transpiler) emitFunction(n tsmorph.Node) error {
	return tr.emitFunctionAs(n, false)
}

// emitFunctionAs emits a function declaration: `func name(params) ret {...}`
// at top level, or a local closure `name := func(params) ret {...}` when
// closure is set. TS allows function declarations nested inside functions;
// Go does not, so those become closures.
func (tr *transpiler) emitFunctionAs(n tsmorph.Node, closure bool) error {
	return tr.emitFunctionWithName(n, n.Name(), closure)
}

// emitFunctionWithName is emitFunctionAs with an explicit Go name (used for
// CJS exports where the source function is anonymous).
func (tr *transpiler) emitFunctionWithName(n tsmorph.Node, goName string, closure bool) error {
	params, ret, err := tr.signatureFromChildren(n)
	if err != nil {
		return err
	}
	isAsync := n.HasModifier(ast.ModifierFlagsAsync)
	if isAsync {
		tr.usedShim = true
		ret = " *jsrtPromise"
	}
	tr.retStack = append(tr.retStack, strings.TrimSpace(ret))
	defer func() { tr.retStack = tr.retStack[:len(tr.retStack)-1] }()
	if isAsync {
		tr.recordGap(SevApprox, "async", n, "async function via jsrt shim (goroutine-per-call); swap for native concurrency later")
		tr.retStack[len(tr.retStack)-1] = "any"
	}
	head := "func " + goName
	if closure {
		head = goName + " := func"
	}
	tr.out.line(head + "(" + params + ")" + ret + " {")
	tr.out.indent()
	if isAsync {
		tr.out.line("return jsrtAsync(func() any {")
		tr.out.indent()
	}
	if body, ok := n.GetBody(); ok {
		if err := tr.emitBlock(body); err != nil {
			return err
		}
	} else {
		tr.out.line(`panic("not implemented")`)
	}
	if isAsync {
		tr.out.dedent()
		tr.out.line("})")
	}
	tr.out.dedent()
	tr.out.line("}")
	if !closure {
		tr.out.blank()
	}
	return nil
}

// emitVariableStatement emits `const x = ...` / `let x: T = ...`.
func (tr *transpiler) emitVariableStatement(n tsmorph.Node) error {
	vs, _ := n.AsVariableStatement()
	for _, d := range vs.Declarations() {
		name := d.Name()
		init, hasInit := d.Initializer()
		tn, hasType := d.TypeNode()
		var typ string
		if hasType {
			t, err := tr.goType(tn)
			if err != nil {
				return err
			}
			typ = t
		}
		if hasInit {
			// Object literals with a declared type → typed struct literal
			// (the checker types the literal as an anonymous __object).
			if ast.IsObjectLiteralExpression(init.ASTNode()) && typ != "" && typ != "any" {
				expr, err := tr.typedObjectLiteral(init, typ)
				if err != nil {
					return err
				}
				tr.out.line("var " + name + " " + typ + " = " + expr)
				continue
			}
			expr, err := tr.emitExpr(init)
			if err != nil {
				return err
			}
			switch {
			case typ != "" && typ != "any" && strings.HasPrefix(expr, "any(nil)"):
				// A placeholder can't initialize a typed var (`var p string
				// = any(nil)` is not assignable); emit the declaration with
				// the TODO as a trailing comment.
				tr.out.line("var " + name + " " + typ + " " + placeholderComment(expr))
			case typ != "" && typ != "any":
				tr.out.line("var " + name + " " + typ + " = " + expr)
			case !hasType && init.Type().IsNumber():
				// `let s = 0` infers number (→ float64); a bare `:=` would
				// pick Go's int and break arithmetic with other numbers.
				tr.out.line("var " + name + " float64 = " + expr)
			default:
				// `:=` is illegal at package scope; top-level consts without
				// an explicit type become `var x = e` instead.
				if len(tr.retStack) == 0 {
					tr.out.line("var " + name + " = " + expr)
				} else {
					tr.out.line(name + " := " + expr)
				}
			}
			tr.markUsedIfUnused(name, n)
		} else if typ != "" {
			tr.out.line("var " + name + " " + typ)
		} else {
			tr.out.line("var " + name + " any")
		}
	}
	return nil
}

// ---------------------------------------------------------------------------
// Signature helpers
// ---------------------------------------------------------------------------

// signatureFromChildren renders `params) ret` from a node's parameter
// children and call-signature return type. The declared return type node is
// preferred over the checker's text so aliases (Money, uint8) survive.
func (tr *transpiler) signatureFromChildren(n tsmorph.Node) (params, ret string, err error) {
	var ps []string
	// Checker call signature (for contextual/JS types of unannotated params
	// and the return type) — may be empty for non-function nodes.
	var sigCheck []string // checker-rendered param types, aligned by index
	if sigs := n.Type().CallSignatures(); len(sigs) > 0 {
		for _, p := range sigs[0].Parameters() {
			sigCheck = append(sigCheck, p.Type.Text())
		}
	}
	pi := 0
	for _, c := range n.Children() {
		if !ast.IsParameterDeclaration(c.ASTNode()) {
			continue
		}
		name := c.Name()
		tn, ok := c.GetType()
		var typ string
		if ok {
			t, err := tr.goType(tn)
			if err != nil {
				return "", "", err
			}
			typ = t
		} else if pi < len(sigCheck) {
			// No annotation: the checker may still know the type from the
			// contextual/call-site type — that's a tightenable site (and the
			// JSDoc case for JS input).
			typ = "any"
			if ct := sigCheck[pi]; ct != "" && notAnyLike(ct) {
				tr.tightenable("param", c, tr.cleanCheckerType(ct), "any")
			}
		} else {
			typ = "any"
		}
		pi++
		ps = append(ps, name+" "+typ)
	}
	ret = ""
	// Declared return type (syntax-first: keeps alias names).
	if rn, ok := tr.returnTypeNode(n); ok {
		t, err := tr.goType(rn)
		if err != nil {
			return "", "", err
		}
		if t != "" {
			ret = " " + t
			return strings.Join(ps, ", "), ret, nil
		}
	}
	sigs := n.Type().CallSignatures()
	if len(sigs) > 0 && !sigs[0].ReturnType().IsVoid() {
		ret = " " + tr.cleanCheckerType(sigs[0].ReturnType().Text())
	}
	return strings.Join(ps, ", "), ret, nil
}

// returnTypeNode finds the declared return-type child of a function-like
// node (the type node following the parameter list).
func (tr *transpiler) returnTypeNode(n tsmorph.Node) (tsmorph.Node, bool) {
	// ts-go-morph's typed wrappers expose ReturnTypeNode directly.
	switch {
	case ast.IsFunctionDeclaration(n.ASTNode()):
		if fd, ok := n.AsFunctionDeclaration(); ok {
			return fd.ReturnTypeNode()
		}
	case ast.IsMethodDeclaration(n.ASTNode()):
		if md, ok := n.AsMethodDeclaration(); ok {
			return md.ReturnTypeNode()
		}
	}
	// Generic fallback: any type node after the parameter list is the return
	// type.
	for _, c := range n.Children() {
		if ast.IsTypeNode(c.ASTNode()) {
			if isTypeNodeAfterParams(n, c) {
				return c, true
			}
		}
	}
	return tsmorph.Node{}, false
}

// isTypeNodeAfterParams reports whether the type node appears after the
// node's parameter list (i.e. it is the return type, not a param type).
func isTypeNodeAfterParams(n, tn tsmorph.Node) bool {
	lastParamEnd := -1
	for _, c := range n.Children() {
		if ast.IsParameterDeclaration(c.ASTNode()) {
			if c.End() > lastParamEnd {
				lastParamEnd = c.End()
			}
		}
	}
	return lastParamEnd >= 0 && tn.Pos() > lastParamEnd
}
